openapi: "3.1.0"
info:
  title: Time Tracking API
  description: This is a sample server for a time tracking API.
  version: 1.0.0
paths:
  /signup:
    post:
      summary: Sign up a new team
      description: Sign up a new team
      operationId: registerNewTeam
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RegisterNewTeamRequest"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TeamCreatedResponse"
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
  /login:
    post:
      summary: Login
      description: Login to an existing team
      operationId: login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginRequest"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TeamMemberResponse"
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
  /teams/{teamId}/invite:
    post:
      summary: Invite new team member
      description: Invite a new team member to an existing team
      operationId: inviteNewTeamMember
      parameters:
        - name: teamId
          in: path
          description: The ID of the team to invite a new member to
          required: true
          schema:
            type: string
      requestBody:
          required: true
          content:
              application/json:
              schema:
                  $ref: "#/components/schemas/InviteNewTeamMemberRequest"
      responses:
          "200":
              description: OK
              content:
                  application/json:
                  schema:
                      $ref: "#/components/schemas/InviteSentResponse"
          "400":
              description: Bad Request
              content:
                  application/json:
                  schema:
                      $ref: "#/components/schemas/ErrorResponse"
  /teams/{teamId}/members/{memberEmail}:
    delete:
      summary: Remove team member
      description: Remove a team member from an existing team
      operationId: removeTeamMember
      parameters:
        - name: teamId
          in: path
          description: The ID of the team to remove a member from
          required: true
          schema:
            type: string
        - name: memberEmail
          in: path
          description: The email of the member to remove
          required: true
          schema:
            type: string
      responses:
          "200":
              description: OK
              content:
                  application/json:
                  schema:
                      $ref: "#/components/schemas/TeamResponse"
          "400":
              description: Bad Request
              content:
                  application/json:
                  schema:
                      $ref: "#/components/schemas/ErrorResponse"
  /teams/{teamId}/members:
      get:
          summary: Get team members
          description: Get all members of an existing team
          operationId: getTeamMembers
          parameters:
          - name: teamId
            in: path
            description: The ID of the team to get members from
            required: true
            schema:
              type: string
          - name: limit
            in: query
            description: The maximum number of members to return
            required: false
            schema:
              type: integer
          - name: offset
            in: query
            description: The number of members to skip
            required: false
            schema:
                type: integer
          responses:
              "200":
                  description: OK
                  content:
                      application/json:
                      type: array
                      items:
                        schema:
                          $ref: "#/components/schemas/TeamMemberResponse"
              "400":
                  description: Bad Request
                  content:
                      application/json:
                      schema:
                          $ref: "#/components/schemas/ErrorResponse"
components:
    schemas:
        RegisterNewTeamRequest:
          type: object
          properties:
              name:
                type: string
              email:
                type: string
              password:
                type: string
              teamName:
                type: string
        TeamCreatedResponse:
          type: object
          properties:
              team_url:
                type: string
        LoginRequest:
          type: object
          properties:
            email:
              type: string
            password:
              type: string
        TeamResponse:
          type: object
          properties:
            team_url:
              type: string
            name:
              type: string
            email:
              type: string
            members:
              type: array
              items:
                schema:
                  $ref: "#/components/schemas/TeamMemberResponse"
        TeamMemberResponse:
          member_url:
            type: string
          name:
            type: string
          email:
            type: string
          role:
            type: string
        InviteNewTeamMemberRequest:
          type: object
          properties:
            email:
              type: string
            teamName:
              type: string
            role:
              type: string
        InviteSentResponse:
          type: object
          properties:
            inviteUrl:
              type: string
            teamName:
              type: string
        ErrorResponse:
          type: object
          properties:
            errorCode:
              type: integer
            message:
              type: string
