name: Checks and Tests

on:
  pull_request:
    branches: [ "main" ]

jobs:
  check-migration-files:
    name: Validate migration files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Validate migration files
        run: |
          for file in ./db/migration/postgres/*.sql; do
            filename=$(basename "$file")
            if ! [[ "$filename" =~ ^V(\d+)__(\w+)(__(\w+))?\.sql$ ]]; then
              echo "File $filename does not match Flyway migration filename format."
              exit 1
            fi
          done
