name: Checks and Tests

on:
  workflow_dispatch:
    inputs:
      run-info:
        description: 'Only run info'
        type: boolean
        required: false
      baselineOnMigrate:
        description: 'Baseline on migrate'
        type: boolean
        required: false

jobs:
  check-migration-files:
    name: Validate migration files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Validate migration files
        run: |
          for file in ./db/migration/postgres/*.sql; do
            filename=$(basename "$file")
            if ! [[ "$filename" =~ ^V[0-9]+__.*\.sql$ ]]; then
              echo "File $filename does not match Flyway migration filename format."
              exit 1
            fi
          done
